# Dev 分支推送部署到Linux服务器
name: Deploy
on:
  push:
    branches:
      - dev
      - master
jobs:
  build-and-deploy:
    name: Build and deploy to server
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        ARGS: '-avz --delete'
        SOURCE: './'
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.SERVER_PATH }}
